language: php

php:
  - '7.1'
  - nightly

before_install:
  - travis_retry composer self-update
  - pecl install swoole

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/simple-phpunit
