symfony_si_docs_homepage:
    pattern:  /documentation
    defaults: { _controller: SymfonySiDocsBundle:Default:index }

symfony_si_docs_show:
    pattern: /documentation/current/{page}
    defaults: { _controller: SymfonySiDocsBundle:Default:show }
    requirements:
        page: ".+"

