parameters:
#    symfony_si_docs.example.class: SymfonySi\DocsBundle\Example

services:
#    symfony_si_docs.example:
#        class: %symfony_si_docs.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
