symfony_si_cheatsheet:
    resource: "@SymfonySiCheatsheetBundle/Resources/config/routing.yml"
    prefix:   /

symfony_si_ecosystem:
    resource: "@SymfonySiEcosystemBundle/Resources/config/routing.yml"
    prefix:   /

symfony_si_docs:
    resource: "@SymfonySiDocsBundle/Resources/config/routing.yml"
    prefix:   /

symfony_si_blog:
    resource: "@SymfonySiBlogBundle/Resources/config/routing.yml"
    prefix:   /

symfony_si_main:
    resource: "@SymfonySiMainBundle/Resources/config/routing.yml"
    prefix:   /
