version: '2'
services:
  web:
    build: .
    volumes:
      - "../:/var/www/symfony.si"
    depends_on:
      - db_mysql
    image: 'symfony-si:1.0'
  db_mysql:
    image: mysql:5.7
    volumes:
      - "./.data/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony_si
      MYSQL_USER: symfonysi
      MYSQL_PASSWORD: password
