symfony_si_main_homepage:
    pattern:  /
    defaults: { _controller: SymfonySiMainBundle:Default:index }

symfony_si_main_copyright:
    pattern: /copyrights
    defaults: { _controller: SymfonySiMainBundle:Default:copyright }

symfony_si_main_join:
    pattern: /join-us
    defaults: { _controller: SymfonySiMainBundle:Default:join }

symfony_si_main_contact:
    pattern: /contact
    defaults: { _controller: SymfonySiMainBundle:Default:contact }

symfony_si_main_contact_success:
    pattern: /contact-succeeded
    defaults: { _controller: SymfonySiMainBundle:Default:contactSuccess }

symfony_si_main_contributors:
    pattern:  /contributors
    defaults: { _controller: SymfonySiMainBundle:Default:contributors }

symfony_si_main_resources:
    pattern:  /resources
    defaults: { _controller: SymfonySiMainBundle:Default:resources }

