parameters:
#    symfony_si_main.example.class: SymfonySi\MainBundle\Example

services:
#    symfony_si_main.example:
#        class: %symfony_si_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
