symfony_si_blog_homepage:
    pattern:  /blog/{_locale}
    defaults: { _controller: SymfonySiBlogBundle:Default:index, _locale: sl }
    requirements:
        _locale: sl|en

symfony_si_blog_show:
    pattern: /blog/{_locale}/{slug}
    defaults: { _controller: SymfonySiBlogBundle:Default:show, _locale: sl }
    requirements:
        _locale: sl|en

