symfony_si_blog_homepage:
    pattern:  /blog
    defaults: { _controller: SymfonySiBlogBundle:Default:index }

symfony_si_blog_show:
    pattern: /blog/{year}/{month}/{day}/{slug}
    defaults: { _controller: SymfonySiBlogBundle:Default:show }
    requirements:
        year: \d+
        month: \d+
        day: \d+

