parameters:
#    symfony_si_blog.example.class: SymfonySi\BlogBundle\Example

services:
#    symfony_si_blog.example:
#        class: %symfony_si_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
